// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdvndE1K83hgakvg6ouLar4uslPLC90aI',
    appId: '1:112659605781:web:3930600d72237f8ef3611c',
    messagingSenderId: '112659605781',
    projectId: 'todo-app-dfe8f',
    authDomain: 'todo-app-dfe8f.firebaseapp.com',
    storageBucket: 'todo-app-dfe8f.appspot.com',
    measurementId: 'G-TXRS26MQJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjScL69PvkWwUrWAffC8xFRw43XfzP_Bk',
    appId: '1:112659605781:android:4e4cd4462c675017f3611c',
    messagingSenderId: '112659605781',
    projectId: 'todo-app-dfe8f',
    storageBucket: 'todo-app-dfe8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwez0whZgasdRef44JjdGSXhGVRdtks-Y',
    appId: '1:112659605781:ios:3d7b2ea47a879b04f3611c',
    messagingSenderId: '112659605781',
    projectId: 'todo-app-dfe8f',
    storageBucket: 'todo-app-dfe8f.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwez0whZgasdRef44JjdGSXhGVRdtks-Y',
    appId: '1:112659605781:ios:1ba62d1879402825f3611c',
    messagingSenderId: '112659605781',
    projectId: 'todo-app-dfe8f',
    storageBucket: 'todo-app-dfe8f.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
